name: "Build QModem for Linksys EA7500 v2"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Install Build Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison gawk gcc-multilib g++-multilib \
          gettext git libncurses5-dev libssl-dev python3-venv rsync unzip zlib1g-dev file wget

      - name: Download OpenWrt 25.12 SDK (ramips/mt7621)
        run: |
          wget -q https://downloads.openwrt.org/releases/25.12.0/targets/ramips/mt7621/openwrt-sdk-25.12.0-ramips-mt7621_gcc-14.3.0_musl.Linux-x86_64.tar.zst
          tar --zstd -xvf openwrt-sdk-*.tar.zst
          rm openwrt-sdk-*.tar.zst
          mv openwrt-sdk-* sdk

      - name: Build QModem Package
        run: |
          # Copy source code ke folder package SDK
          mkdir -p sdk/package/luci-app-qmodem
          cp -r application/qmodem/* sdk/package/luci-app-qmodem/
          
          cd sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
          echo "CONFIG_PACKAGE_luci-app-qmodem=m" > .config
          make defconfig
          make package/luci-app-qmodem/compile V=s -j$(nproc)

      - name: Organize Artifacts
        run: |
          mkdir -p output
          find sdk/bin/ -type f \( -name "*.apk" -o -name "*.ipk" \) -exec cp {} output/ \;

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: QModem-Linksys-EA7500v2
          path: output/
